# Substitute <interface> with real name

HTTP_BIND=:8082
DB_PATH=/var/lib/tanlnode/<interface>/db
TLS_CLIENT_CERT=/etc/tanlnode/<interface>/client.cert
TLS_SERVER_CERT=/etc/tanlnode/<interface>/server.cert
TLS_SERVER_KEY=/etc/tanlnode/<interface>/server.key
WG_EXEC_PATH=/usr/bin/wg

# Change

WG_ALLOC_NETS=10.82.0.0/16,fd80:1234::/100
WG_PUBLIC_KEY=<public key>
WG_ENDPOINT_HOST=127.0.0.1
WG_ENDPOINT_PORTS=100,101,102
WG_DNS=10.82.0.1
WG_MTU=1420
WG_PERSISTENT_KEEPALIVE=27
