// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

type Subnet struct {
	ID         int64
	Prefix     string
	PeerID     *int64
	Comment    string
	MayOverlap bool
}
