// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"time"
)

type Peer struct {
	ID                  int64
	PublicKeyBase64     string
	IsEnabled           bool
	PresharedKeyBase64  string
	Endpoint            string
	PersistentKeepalive int64
	Owner               string
	LatestHandshakeAt   *time.Time
	LatestEndpoint      *string
}

type PeerStat struct {
	ID          int64
	TimestampMs int64
	PeerID      int64
	Rx          int64
	Tx          int64
}

type Subnet struct {
	ID         int64
	Prefix     string
	PeerID     *int64
	Comment    string
	MayOverlap bool
}
