// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
	"time"
)

const addPeer = `-- name: AddPeer :one

INSERT INTO peers (
    public_key_base64,
    is_enabled,
    preshared_key_base64,
    endpoint,
    persistent_keepalive,
    owner
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
RETURNING id, public_key_base64, is_enabled, preshared_key_base64, endpoint, persistent_keepalive, owner, latest_handshake_at, latest_endpoint
`

type AddPeerParams struct {
	PublicKeyBase64     string
	IsEnabled           bool
	PresharedKeyBase64  string
	Endpoint            string
	PersistentKeepalive int64
	Owner               string
}

// - ======= Peers =======
func (q *Queries) AddPeer(ctx context.Context, arg AddPeerParams) (Peer, error) {
	row := q.db.QueryRowContext(ctx, addPeer,
		arg.PublicKeyBase64,
		arg.IsEnabled,
		arg.PresharedKeyBase64,
		arg.Endpoint,
		arg.PersistentKeepalive,
		arg.Owner,
	)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.PublicKeyBase64,
		&i.IsEnabled,
		&i.PresharedKeyBase64,
		&i.Endpoint,
		&i.PersistentKeepalive,
		&i.Owner,
		&i.LatestHandshakeAt,
		&i.LatestEndpoint,
	)
	return i, err
}

const addSubnet = `-- name: AddSubnet :one

INSERT INTO subnets (
    prefix,
    peer_id,
    comment,
    may_overlap
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, prefix, peer_id, comment, may_overlap
`

type AddSubnetParams struct {
	Prefix     string
	PeerID     *int64
	Comment    string
	MayOverlap bool
}

// - ======= Subnets =======
func (q *Queries) AddSubnet(ctx context.Context, arg AddSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, addSubnet,
		arg.Prefix,
		arg.PeerID,
		arg.Comment,
		arg.MayOverlap,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.PeerID,
		&i.Comment,
		&i.MayOverlap,
	)
	return i, err
}

const deleteSubnet = `-- name: DeleteSubnet :execrows
DELETE FROM subnets WHERE id = ?1
`

func (q *Queries) DeleteSubnet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubnet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllSubnets = `-- name: GetAllSubnets :many
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
`

func (q *Queries) GetAllSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.PeerID,
			&i.Comment,
			&i.MayOverlap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastPeerStat = `-- name: GetLastPeerStat :one
SELECT id, timestamp_ms, peer_id, rx, tx FROM peer_stats
WHERE peer_id = ?1 AND coalesce(timestamp_ms <= ?2, TRUE)
ORDER BY timestamp_ms DESC
LIMIT 1
`

type GetLastPeerStatParams struct {
	PeerID  int64
	UntilMs *int64
}

func (q *Queries) GetLastPeerStat(ctx context.Context, arg GetLastPeerStatParams) (PeerStat, error) {
	row := q.db.QueryRowContext(ctx, getLastPeerStat, arg.PeerID, arg.UntilMs)
	var i PeerStat
	err := row.Scan(
		&i.ID,
		&i.TimestampMs,
		&i.PeerID,
		&i.Rx,
		&i.Tx,
	)
	return i, err
}

const getPeerByPublicKey = `-- name: GetPeerByPublicKey :one
SELECT id, public_key_base64, is_enabled, preshared_key_base64, endpoint, persistent_keepalive, owner, latest_handshake_at, latest_endpoint FROM peers
WHERE public_key_base64 = ?1
LIMIT 1
`

func (q *Queries) GetPeerByPublicKey(ctx context.Context, publicKeyBase64 string) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByPublicKey, publicKeyBase64)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.PublicKeyBase64,
		&i.IsEnabled,
		&i.PresharedKeyBase64,
		&i.Endpoint,
		&i.PersistentKeepalive,
		&i.Owner,
		&i.LatestHandshakeAt,
		&i.LatestEndpoint,
	)
	return i, err
}

const getPeerSubnets = `-- name: GetPeerSubnets :many
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
WHERE peer_id = ?1
`

func (q *Queries) GetPeerSubnets(ctx context.Context, peerID *int64) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getPeerSubnets, peerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.PeerID,
			&i.Comment,
			&i.MayOverlap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeers = `-- name: GetPeers :many
SELECT id, public_key_base64, is_enabled, preshared_key_base64, endpoint, persistent_keepalive, owner, latest_handshake_at, latest_endpoint FROM peers
WHERE owner = COALESCE(?1, owner)
ORDER BY public_key_base64
`

func (q *Queries) GetPeers(ctx context.Context, owner *string) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, getPeers, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.PublicKeyBase64,
			&i.IsEnabled,
			&i.PresharedKeyBase64,
			&i.Endpoint,
			&i.PersistentKeepalive,
			&i.Owner,
			&i.LatestHandshakeAt,
			&i.LatestEndpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservedSubnets = `-- name: GetReservedSubnets :many
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
WHERE peer_id IS NULL
`

func (q *Queries) GetReservedSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getReservedSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.PeerID,
			&i.Comment,
			&i.MayOverlap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
WHERE id = ?1
`

func (q *Queries) GetSubnetByID(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByID, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.PeerID,
		&i.Comment,
		&i.MayOverlap,
	)
	return i, err
}

const putPeerStat = `-- name: PutPeerStat :one

INSERT INTO peer_stats (
    timestamp_ms,
    peer_id,
    rx,
    tx
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, timestamp_ms, peer_id, rx, tx
`

type PutPeerStatParams struct {
	TimestampMs int64
	PeerID      int64
	Rx          int64
	Tx          int64
}

// - ======= Stats =======
func (q *Queries) PutPeerStat(ctx context.Context, arg PutPeerStatParams) (PeerStat, error) {
	row := q.db.QueryRowContext(ctx, putPeerStat,
		arg.TimestampMs,
		arg.PeerID,
		arg.Rx,
		arg.Tx,
	)
	var i PeerStat
	err := row.Scan(
		&i.ID,
		&i.TimestampMs,
		&i.PeerID,
		&i.Rx,
		&i.Tx,
	)
	return i, err
}

const removeOldStats = `-- name: RemoveOldStats :exec
DELETE FROM peer_stats
WHERE timestamp_ms <= ?1
`

func (q *Queries) RemoveOldStats(ctx context.Context, oldestMs int64) error {
	_, err := q.db.ExecContext(ctx, removeOldStats, oldestMs)
	return err
}

const removePeer = `-- name: RemovePeer :execrows
DELETE FROM peers
WHERE public_key_base64 = ?1
`

func (q *Queries) RemovePeer(ctx context.Context, publicKeyBase64 string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removePeer, publicKeyBase64)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePeer = `-- name: UpdatePeer :one
UPDATE peers
SET
    is_enabled = ?1,
    preshared_key_base64 = ?2,
    endpoint = ?3,
    persistent_keepalive = ?4,
    owner = ?5
WHERE public_key_base64 = ?6
RETURNING id, public_key_base64, is_enabled, preshared_key_base64, endpoint, persistent_keepalive, owner, latest_handshake_at, latest_endpoint
`

type UpdatePeerParams struct {
	IsEnabled           bool
	PresharedKeyBase64  string
	Endpoint            string
	PersistentKeepalive int64
	Owner               string
	PublicKeyBase64     string
}

func (q *Queries) UpdatePeer(ctx context.Context, arg UpdatePeerParams) (Peer, error) {
	row := q.db.QueryRowContext(ctx, updatePeer,
		arg.IsEnabled,
		arg.PresharedKeyBase64,
		arg.Endpoint,
		arg.PersistentKeepalive,
		arg.Owner,
		arg.PublicKeyBase64,
	)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.PublicKeyBase64,
		&i.IsEnabled,
		&i.PresharedKeyBase64,
		&i.Endpoint,
		&i.PersistentKeepalive,
		&i.Owner,
		&i.LatestHandshakeAt,
		&i.LatestEndpoint,
	)
	return i, err
}

const updatePeerHandshakeData = `-- name: UpdatePeerHandshakeData :execrows
UPDATE peers
SET
    latest_handshake_at = ?1,
    latest_endpoint = ?2
WHERE id = ?3
`

type UpdatePeerHandshakeDataParams struct {
	LatestHandshakeAt *time.Time
	LatestEndpoint    *string
	ID                int64
}

func (q *Queries) UpdatePeerHandshakeData(ctx context.Context, arg UpdatePeerHandshakeDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePeerHandshakeData, arg.LatestHandshakeAt, arg.LatestEndpoint, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
