// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
)

const addSubnet = `-- name: AddSubnet :one
INSERT INTO subnets (
    prefix,
    peer_id,
    comment,
    may_overlap
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, prefix, peer_id, comment, may_overlap
`

type AddSubnetParams struct {
	Prefix     string
	PeerID     *int64
	Comment    string
	MayOverlap bool
}

func (q *Queries) AddSubnet(ctx context.Context, arg AddSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, addSubnet,
		arg.Prefix,
		arg.PeerID,
		arg.Comment,
		arg.MayOverlap,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.PeerID,
		&i.Comment,
		&i.MayOverlap,
	)
	return i, err
}

const deleteSubnet = `-- name: DeleteSubnet :execrows
DELETE FROM subnets WHERE id = ?1
`

func (q *Queries) DeleteSubnet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubnet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllSubnets = `-- name: GetAllSubnets :many
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
`

func (q *Queries) GetAllSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.PeerID,
			&i.Comment,
			&i.MayOverlap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservedSubnets = `-- name: GetReservedSubnets :many
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
WHERE peer_id IS NULL
`

func (q *Queries) GetReservedSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, getReservedSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.PeerID,
			&i.Comment,
			&i.MayOverlap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT id, prefix, peer_id, comment, may_overlap FROM subnets
WHERE id = ?1
`

func (q *Queries) GetSubnetByID(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnetByID, id)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.PeerID,
		&i.Comment,
		&i.MayOverlap,
	)
	return i, err
}
