// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstat

import (
	"context"
)

const getLastPeerStat = `-- name: GetLastPeerStat :one
SELECT peer_id, tx_bytes, rx_bytes, timestamp FROM peer_stats
WHERE peer_id = ?1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLastPeerStat(ctx context.Context, peerID int64) (PeerStat, error) {
	row := q.db.QueryRowContext(ctx, getLastPeerStat, peerID)
	var i PeerStat
	err := row.Scan(
		&i.PeerID,
		&i.TxBytes,
		&i.RxBytes,
		&i.Timestamp,
	)
	return i, err
}

const getPeerStatOlderThan = `-- name: GetPeerStatOlderThan :one
SELECT peer_id, tx_bytes, rx_bytes, timestamp FROM peer_stats
WHERE
    peer_id = ?1 AND
    timestamp < ?2
ORDER BY timestamp DESC
LIMIT 1
`

type GetPeerStatOlderThanParams struct {
	PeerID    int64
	Timestamp int64
}

func (q *Queries) GetPeerStatOlderThan(ctx context.Context, arg GetPeerStatOlderThanParams) (PeerStat, error) {
	row := q.db.QueryRowContext(ctx, getPeerStatOlderThan, arg.PeerID, arg.Timestamp)
	var i PeerStat
	err := row.Scan(
		&i.PeerID,
		&i.TxBytes,
		&i.RxBytes,
		&i.Timestamp,
	)
	return i, err
}

const putStat = `-- name: PutStat :exec
INSERT INTO peer_stats (
    peer_id,
    tx_bytes,
    rx_bytes,
    timestamp    
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type PutStatParams struct {
	PeerID    int64
	TxBytes   int64
	RxBytes   int64
	Timestamp int64
}

func (q *Queries) PutStat(ctx context.Context, arg PutStatParams) error {
	_, err := q.db.ExecContext(ctx, putStat,
		arg.PeerID,
		arg.TxBytes,
		arg.RxBytes,
		arg.Timestamp,
	)
	return err
}
