// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/peers": {
            "get": {
                "description": "Returns a list of peers, optionally filtered by owner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "List peers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by owner",
                        "name": "owner",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.PeerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new peer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Add a new peer",
                "parameters": [
                    {
                        "description": "peer",
                        "name": "peer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AddPeerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.NewPeerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/peers/{pubkey}": {
            "get": {
                "description": "Returns the peer identified by the given key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Get a peer by key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer key",
                        "name": "pubkey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PeerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Update a peer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer key",
                        "name": "pubkey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated peer object",
                        "name": "peer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdatePeerRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes the peer identified by the given key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Delete a peer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Peer key",
                        "name": "pubkey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/peers/{pubkey}/subnets": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subnets"
                ],
                "summary": "Get peer's subnets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "peer public key",
                        "name": "pubkey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.SubnetResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Peer not found",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/subnets/reserved": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subnets"
                ],
                "summary": "Get reserved subnets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.SubnetResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subnets"
                ],
                "summary": "Reserve a subnet",
                "parameters": [
                    {
                        "description": "subnet",
                        "name": "subnet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ReserveSubnetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.SubnetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    },
                    "409": {
                        "description": "Subnet overlaps with existing",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/subnets/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subnets"
                ],
                "summary": "Delete a subnet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subnet id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/main.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.AddPeerRequest": {
            "type": "object",
            "properties": {
                "allowed_addresses": {
                    "description": "List of CIDR subnets that are going to be assigned to the created peer.\nIf empty, then one address (/32 for v4, /128 v6) per each configured node's net\nwill be assigned randomly.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "mayOverlap": {
                                "description": "Subnet is not treated as exclusive for one peer, so it may overlap with other subnets,\nand it is not taken into account by random address allocation.",
                                "type": "boolean"
                            },
                            "subnet": {
                                "type": "string"
                            }
                        }
                    }
                },
                "endpoint": {
                    "description": "optional",
                    "type": "string"
                },
                "owner": {
                    "description": "optional",
                    "type": "string"
                },
                "persistent_keepalive": {
                    "description": "optional",
                    "type": "integer"
                },
                "preshared_key_base64": {
                    "description": "optional",
                    "type": "string"
                },
                "public_key_base64": {
                    "description": "optional, omit to generate new random private key (not saved on the node)",
                    "type": "string"
                },
                "random_preshared_key": {
                    "description": "If set, then a new random preshared key will be generated.\nThis flag beign set is mutually exclusive with ` + "`" + `preshared_key_base64` + "`" + ` beign non-null.",
                    "type": "boolean"
                }
            }
        },
        "main.NewPeerResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/main.WGQuickConfig"
                },
                "peer": {
                    "$ref": "#/definitions/main.PeerResponse"
                }
            }
        },
        "main.PeerResponse": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "description": "optional",
                    "type": "string"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "owner": {
                    "description": "optional",
                    "type": "string"
                },
                "persistent_keepalive": {
                    "description": "optional",
                    "type": "integer"
                },
                "preshared_key_base64": {
                    "description": "optional",
                    "type": "string"
                },
                "public_key_base64": {
                    "type": "string"
                }
            }
        },
        "main.ReserveSubnetRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Can be empty",
                    "type": "string"
                },
                "may_overlap": {
                    "type": "boolean"
                },
                "prefix": {
                    "type": "string"
                }
            }
        },
        "main.SubnetResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "may_overlap": {
                    "type": "boolean"
                },
                "prefix": {
                    "type": "string"
                }
            }
        },
        "main.UpdatePeerRequest": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "description": "optional",
                    "type": "string"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "owner": {
                    "description": "optional",
                    "type": "string"
                },
                "persistent_keepalive": {
                    "description": "optional",
                    "type": "integer"
                },
                "preshared_key_base64": {
                    "description": "optional",
                    "type": "string"
                }
            }
        },
        "main.WGQuickConfig": {
            "type": "object",
            "properties": {
                "interface": {
                    "type": "object",
                    "properties": {
                        "addresses": {
                            "description": "CIDRs",
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "dns": {
                            "description": "based on configuration (optional)",
                            "type": "string"
                        },
                        "mtu": {
                            "description": "based on configuration (optional)",
                            "type": "integer"
                        },
                        "private_key": {
                            "description": "set to a newly generated one only if no public key was provided in the request",
                            "type": "string"
                        }
                    }
                },
                "node_peer": {
                    "type": "object",
                    "properties": {
                        "endpoint": {
                            "type": "string"
                        },
                        "persistent_keepalive": {
                            "description": "based on configuration (optional)",
                            "type": "integer"
                        },
                        "preshared_key": {
                            "description": "set only if preshared key was given, or random preshared key generation was requested",
                            "type": "string"
                        },
                        "public_key": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
